# Generated by Django 5.0.3 on 2024-03-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_videoitem_processed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='videoitem',
            name='status',
            field=models.TextField(default='processing'),
        ),
    ]
