# Generated by Django 5.0.3 on 2024-03-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0003_videoitem_path_videoitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='status',
            field=models.TextField(),
        ),
    ]
