# Generated by Django 5.0.3 on 2024-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0004_alter_videoitem_path_alter_videoitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='path',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
