# Generated by Django 5.0.3 on 2024-03-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0008_alter_videoitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('processed', 'Processed'), ('uploading', 'Uploading')], default='processing', max_length=20),
        ),
    ]
